### ISSUE TITLE
(doc) Questions on back-propagation algorithm

### ISSUE THREAD

**Issue by qlibp** [minitorch/Module-1#1]
> Initialize a queue with the final variable+derivative.
> While the queue is not empty, pull a variable+derivative from the queue.
> If the variable is a leaf then add its final derivative (_add_deriv) and loop to (1).
> If the variables is not a leaf call .chain_rule on the last function that created it with derivative as 𝑑𝑜𝑢𝑡.
> Loop through all the variables+derivative produced by the chain rule.
> If the variable is in the queue (check .name), add to its current derivativ
> Otherwise, add to the queue.

Actually, it's not necessary to `Loop through all the variables+derivative produced by the chain rule.` Even though we don't check for repetition, the chain rule and sum rule will automatically accumulate the deriv to the leaf node.

**Comment by srush** [comment]
Right... We could drop that step for simplicity. Speed-wise, implemented with a good hashing algorithm it will make things faster. But I think you make a good point.

**Comment by qlibp** [comment]
> Right... We could drop that step for simplicity. Speed-wise, implemented with a good hashing algorithm it will make things faster. But I think you make a good point.

I see, seems that it would be niec to address this in the doc page and leave it as an optional exercise.

**Comment by qlibp** [comment]
Besides, I don't know if I implement the algo right. I need to filter out those `Variable` with its `self.history=None`(these Variables are constant that are input for `ScalarFunction` which got wrapped into Variable), which is not mentioned in the algo description and I struggle to find the bug for a long time.

**Comment by srush** [comment]
This is very useful feedback, I will clarify both points in the docs and update the example. 

Please keep sending comments or clarifications as you go.

**Comment by srush** [comment]
Right. History=None means the variable is a constant or doesn't require a derivative. I will add a property so that is less confusing and update the docs in chain_rule. 

We're you able to pass the tests otherwise?

**Comment by qlibp** [comment]
Another typo found in the [doc](https://minitorch.github.io/module1.html#task-1-5-training). I just run the task 1.5 and found that the figure in doc is not in proper order. The second one should be Xor curve rather than a hyperplane.

**Comment by srush** [comment]
Okay, I think I got most of these changes. I will leave this issue as a reminder to make the backprop docs better.
