### ISSUE TITLE
Bug Report: some thing in class LT(ScalarFunction)

### ISSUE THREAD

**Issue by ifoyooo** [minitorch/Module-1#10]
So sorry to bother you. 

Thanks for your nice code and tutorial, I really benefited a lot after finish module-1. But some thing seems to be wrong with the Class LT. It does not define a backward function, but the method will be tested in task1_4. Am i correct? Or am I misunderstanding something? Thank you so much.
```python

class LT(ScalarFunction):
    "Less-than function :math:`f(x) =` 1.0 if x is less than y else 0.0"

    @staticmethod
    def forward(ctx, a, b):
        # TODO: Implement for Task 1.2.
        raise NotImplementedError('Need to implement for Task 1.2')
        # TODO: Implement for Task 1.2.
        raise NotImplementedError('Need to implement for Task 1.2')
        # TODO: Implement for Task 1.4.
        raise NotImplementedError('Need to implement for Task 1.4')
```

**Comment by srush** [comment]
Thank you! This was an error in our module generation code. I pushed a small fix just now. 

The intention is to implement the backward() function as well.
