### ISSUE TITLE
(bug) code that's not covered in the test case and happens to be buggy

### ISSUE THREAD

**Issue by qlibp** [minitorch/Module-1#2]
```python
class LT(ScalarFunction):
    "Less-than function"

    @staticmethod
    def forward(ctx, a, b):
        return 1.0 if a < b else 0.0

    @staticmethod
    def backward(ctx, d_output):
        return 0.0. # bug, it should be: return 0.0, 0.0
```

**Comment by srush** [comment]
Thanks! Fixed and will be released in the next push. I am also adding a `coverage` command to make sure we don't run into this issue again.

**Comment by qlibp** [comment]
Actually, I do not quite understand why it should return 0 in the backward function. Any explanation? Thx!

**Comment by srush** [comment]
LT as a function is always either 0 or 1. Therefore its gradient is always 0 (since minor changes don't change the value).
