### ISSUE TITLE
Assert in chain rule tests

### ISSUE THREAD

**Issue by ionuttamas** [minitorch/Module-1#8]
In https://github.com/minitorch/Module-1/blob/master/tests/test_autodiff.py line 53, are we sure that this assert is correct:
`assert variable_with_deriv.deriv == 5`?

Shouldn't it be `assert variable_with_deriv.deriv == 5 * 10`?

As it will only return a single variable with derivative (as the constants are dropped from the chain_rule) and multiplication is commutative.

**Comment by srush** [comment]
These functions are a bit confusing and should have more clear naming. 

However, that test is correct. If you look at the backward it is calling you can see that it just passes d_output back. which is 5. 

```
class Temp(minitorch.FunctionBase):
    "Implements additions"

    @staticmethod
    def backward(ctx, d_output):
        return d_output, d_output
```

**Comment by ionuttamas** [comment]
@srush 
But this is not true, as the function is **Temp2** (not **Temp1**) at the **line 53 assert**: 

`class Temp2(minitorch.FunctionBase):
    "Implements additions"

    @staticmethod
    def backward(ctx, d_output):
        x = ctx.saved_values
        return d_output, x * d_output`

and that's why I think it should be 5 * 10 (as in the **line 45 assert**); this should be true regardless as is the same function, just the order of parameters change compared to the **line 45 assert**.

**Comment by srush** [comment]
Oh sorry I read the wrong line. 

On line 53 it is temp2, but the var is switched. It's the first one (not times x). Constants are dropped.

**Comment by srush** [comment]
Order of the vars does matter here. Backward returns correspond to forward arg order.
